services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: portfoliohamriyassine-portfoliohamriyassine.d.aivencloud.com
      PMA_PORT: 28606
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - ./certs/ca.pem:/etc/phpmyadmin/certs/ca.pem:ro
