version: "3.9"
services:
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1   # permet de saisir un hôte manuellement
    volumes:
      # fichier config phpMyAdmin pour SSL Aiven
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      # ton certificat CA Aiven
      - ./certs/ca.pem:/etc/phpmyadmin/certs/ca.pem:ro

volumes:
  db_data: